- name: Deploy Maven App Locally
  hosts: local
  become: true

  tasks:
    - name: Ensure curl is installed
      apt:
        name: curl
        state: present
        update_cache: yes

    - name: Copy jar to /opt/app.jar
      copy:
        src: target/dev8-1.0-SNAPSHOT.jar
        dest: /opt/app.jar
